# rubocop config files for small Rails4/Ruby2 project
# blog post: http://joanswork.com/rubocop-rails-getting-started/
# TODO: copy to gist

# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'config.ru'

  Exclude:
    - 'db/schema.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - 'app/views/**/*.html.erb'
    - 'bin/*'
    - 'tmp/*'
    - 'node_modules/*'
    - 'log/*'

IndentationConsistency:
  EnforcedStyle: 'rails'

Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
