# rubocop config files for small Rails4/Ruby2 project
# blog post: http://joanswork.com/rubocop-rails-getting-started/
# TODO: copy to gist

# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - 'db/schema.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'app/views/**/*.html.erb'
    - 'bin/*'

IndentationConsistency:
  EnforcedStyle: 'rails'

Documentation:
  Enabled: false

# SpaceInsideHashLiteralBraces:
#   EnforcedStyle: no_space

# MethodLength:
#   Max: 20 # revisit

HasAndBelongsToMany: # being used for a reason
  Enabled: false

# complains about Gemfile
Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
