# ./spec/.rubocop.yml

inherit_from:
  - ../.rubocop.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - '*_helper.rb'

Metrics/BlockLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
